[build]
  command = "npm run prepare && npm run check && npm run lint && npx playwright install && npm run test && npm run build"
  publish = "build/"
  functions = "functions/"
  environment = { NODE_VERSION = "22" }
