[build]
  command = "npm ci && npm audit && npm audit signatures && npm run prepare && npm run check && npm run lint && npm run build"
  publish = "build/"
  functions = "functions/"
  environment = { NODE_VERSION = "24.20.0", NPM_VERSION = "12.0.2" }
