[build]
  publish = "build/"
  command = "yarn build"
  environment = { INLINE_RUNTIME_CHUNK = "false", REACT_APP_DEPLOY_ENV = "production" }

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache, max-age=0"

[[headers]]
  for = "/"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; script-src 'self'; manifest-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' https://x46g8u90qd.execute-api.ap-southeast-1.amazonaws.com"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Feature-Policy = "geolocation 'none'; microphone 'none'; camera 'none'; fullscreen 'none'; payment 'none'; sync-xhr 'none'"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
