[build]
  command = "npm run prepare && npm run check && npm run lint && npm run test && npm run build"
  publish = "build/"
  functions = "functions/"
  environment = { NODE_VERSION = "22" }

[[plugins]]
  package = "netlify-plugin-playwright-cache"
