[build]
  command = "npm run test && npm run build"
  publish = "build/"
  functions = "functions/"
  environment = { NODE_VERSION = "16.14" }

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    cache-control = "no-cache, max-age=0"

[[headers]]
  for = "/"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; script-src 'self'; manifest-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' https://asia-southeast1-monarch-public.cloudfunctions.net"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Feature-Policy = "geolocation 'none'; microphone 'none'; camera 'none'; fullscreen 'none'; payment 'none'; sync-xhr 'none'"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
