name: Check Netlify
on:
  push:
    branches:
      - main
jobs:
  wait-for-netlify-build:
    name: Wait for netlify build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: node .github/scripts/wait-for-netlify.js
